package analisadorlexico;

public enum Tokens {
    PALAVRA_RESERVADA,
    IDENTIFICADOR,
    NUMERO_INTEIRO,
    NUMERO_REAL,
    OPERADOR_ARITMETICO,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    SIMBOLO_ESPECIAL,
    ATRIBUICAO,
    FIM,
    CONSTANTE_STRING,
    CONSTANTE_CHAR,
    DESCONHECIDO
}